import {useState} from 'react'
import {Link} from 'react-router-dom'
import {useAuth} from '../auth.jsx'
import {useSocial} from '../social.jsx'
import {Avatar,ago,Chip,VerifiedBadge} from '../components/ui.jsx'
import {Icon} from '../components/Layout.jsx'
function Post({p}){
  const s=useSocial(),{isAdmin}=useAuth(),[open,setOpen]=useState(false),[c,setC]=useState(''),[editing,setEditing]=useState(false),[editText,setEditText]=useState(p.text),[editTag,setEditTag]=useState(p.tag),[error,setError]=useState(''),a=s.person(p.by),liked=p.likes.includes(s.me),mine=p.by===s.me
  const saveEdit=async e=>{e.preventDefault();if(!editText.trim())return;try{await s.editPost(p.id,editText,editTag);setEditing(false);setError('')}catch(x){setError(x.message)}}
  const removePost=async()=>{if(!window.confirm('Delete this post?'))return;try{await s.deletePost(p.id);setError('')}catch(x){setError(x.message)}}
  return <article className="card p-4"><header className="flex items-center gap-3"><Avatar p={a}/><div className="flex-1 leading-tight"><Link to={`/u/${p.by}`} className="font-semibold hover:text-primary-container">{a?.name||p.by}<VerifiedBadge verified={a?.verified}/></Link><div className="text-xs text-ink-2">{ago(p.t)}</div></div><span className="pill">{p.tag}</span>{mine&&<div className="flex gap-2"><button type="button" className="btn-outline !px-2 !py-1 text-xs" onClick={()=>{setEditing(!editing);setEditText(p.text);setEditTag(p.tag)}}>{editing?'Cancel':'Edit'}</button><button type="button" className="btn-outline !px-2 !py-1 text-xs text-error" onClick={removePost}>Delete</button></div>}</header>
   {editing?<form onSubmit={saveEdit} className="mt-3 space-y-2"><textarea className="field" maxLength={280} rows={3} value={editText} onChange={e=>setEditText(e.target.value)} aria-label="Edit post"/><div className="flex flex-wrap items-center gap-2"><select className="field !w-auto" value={editTag} onChange={e=>setEditTag(e.target.value)} aria-label="Post topic">{['General',p.tag,...(s.person(s.me)?.interests||[])].filter((x,i,a)=>a.indexOf(x)===i).map(x=><option key={x}>{x}</option>)}</select><button className="btn-primary" disabled={!editText.trim()}>Save changes</button></div></form>:<p className="mt-3 leading-7">{p.text}</p>}
   {error&&<p role="alert" className="mt-2 text-sm text-error">{error}</p>}
   <footer className="mt-3 flex gap-5 text-sm"><button aria-pressed={liked} onClick={async()=>{try{await s.toggleLike(p.id);setError('')}catch(x){setError(x.message)}}} className={liked?'font-semibold text-primary-container':'text-ink-2'}><Icon n="favorite"/> {p.likes.length}</button><button onClick={()=>setOpen(!open)} className="text-ink-2" aria-expanded={open}><Icon n="chat_bubble"/> {p.comments.length}</button></footer>
   {open&&<div className="mt-3 space-y-3 border-t border-outline-variant pt-3">{p.comments.map((m,i)=>{const id=m.id||`${p.id}-${i}`,mine=m.by===s.me;return <div key={id} className="flex gap-2 text-sm"><Avatar p={s.person(m.by)} size={28}/><div className="flex-1"><b>{s.person(m.by)?.name}</b> <span className="text-xs text-ink-2">{ago(m.t)}</span><br/>{m.text}<div className="mt-1 flex gap-3 text-xs text-ink-2"><button onClick={()=>s.reportComment('post',p.id,id)} className="hover:text-error">Report</button>{mine&&<button onClick={()=>s.deleteComment('post',p.id,id)} className="hover:text-error">Delete</button>}{isAdmin&&<button onClick={()=>s.adminDeleteComment('post',p.id,id)} className="hover:text-error">Admin delete</button>}</div></div></div>})}
    <form onSubmit={async e=>{e.preventDefault();if(c.trim()){try{await s.addComment(p.id,c.trim());setC('')}catch(x){setError(x.message)}}}} className="flex gap-2"><input className="field" placeholder="Write a reply" aria-label="Reply" value={c} onChange={e=>setC(e.target.value)}/><button className="btn-primary" disabled={!c.trim()}>Reply</button></form></div>}</article>}
export default function Feed(){
  const {user,isAdmin,banEmail}=useAuth(),s=useSocial(),[t,setT]=useState(''),[tag,setTag]=useState('General'),[mine,setMine]=useState(false),[error,setError]=useState('')
  const mi=user.interests||[],posts=s.posts.filter(p=>!mine||mi.includes(p.tag)||s.conns.includes(p.by)||p.by===s.me)
  const sugg=s.people.filter(p=>p.uid!==s.me&&!s.conns.includes(p.uid)).sort((a,b)=>s.shared(b).length-s.shared(a).length).slice(0,3)
  return <div className="grid gap-8 lg:grid-cols-12">
   <aside className="space-y-4 lg:col-span-3"><div className="panel p-4"><Avatar p={user} size={48}/><Link to={`/u/${user.uid}`} className="mt-2 block font-serif text-xl font-semibold hover:text-primary-container">{user.name}</Link><p className="text-xs text-ink-2">@{user.uid} · {user.college}</p>
    <div className="mt-3 flex flex-wrap gap-1">{mi.map(i=><span key={i} className="pill">{i}</span>)}</div><p className="mt-3 text-sm text-ink-2">{s.conns.length} connections</p></div></aside>
   <section className="space-y-4 lg:col-span-6">
    {s.canPost?<form onSubmit={async e=>{e.preventDefault();setError('');try{await s.addPost(t.trim(),tag);setT('')}catch(x){setError(x.message||'Could not publish post.')}}} className="panel p-4"><label className="label" htmlFor="np">Share an update or look for people</label>
     <textarea id="np" maxLength={280} rows={3} className="field" placeholder="What are you building or looking for?" value={t} onChange={e=>setT(e.target.value)}/>
     <div className="mt-2 flex flex-wrap items-center gap-3"><select aria-label="Topic" className="field !w-auto" value={tag} onChange={e=>setTag(e.target.value)}>{['General',...mi].map(x=><option key={x}>{x}</option>)}</select><span className="text-xs text-ink-2">{t.length}/280</span><button className="btn-primary ml-auto" disabled={!t.trim()}>Post</button></div></form>
    :<div className="panel p-4 text-sm text-ink-2">Only students verified with an <b>@sudoon.ac.in</b> email can create posts. You can still comment, like, connect, and message other users.</div>}
    {error&&<p role="alert" className="rounded border border-error bg-error-wash p-3 text-sm text-error">{error}</p>}
    <div className="flex gap-2"><Chip on={!mine} onClick={()=>setMine(false)}>Everyone</Chip><Chip on={mine} onClick={()=>setMine(true)}>My interests & connections</Chip></div>
    {!posts.length&&<p className="panel p-6 text-center">Nothing here yet. Connect with people in Discover or post the first update.</p>}
    {posts.sort((a,b)=>b.t-a.t).map(p=><Post key={p.id} p={p}/>)}</section>
   <aside className="space-y-4 lg:col-span-3">{isAdmin&&<div className="panel p-4"><h2 className="text-lg">Moderation reports</h2>{!s.commentReports.length?<p className="mt-2 text-sm text-ink-2">No reports.</p>:s.commentReports.map(r=>{const item=(r.surface==='post'?s.posts:s.clubEvents).find(x=>x.id===r.itemId),comment=item?.comments.find((x,i)=>(x.id||`${r.itemId}-${i}`)===r.commentId),reported=s.person(comment?.by);return <div key={r.id} className="mt-3 border-t border-outline-variant pt-3 text-xs"><p>{comment?.text||'Comment removed'}<br/><b>{reported?.email||comment?.by}</b></p>{comment&&<button className="mt-2 btn-outline !px-2 !py-1" onClick={()=>s.adminDeleteComment(r.surface,r.itemId,r.commentId)}>Remove comment</button>}{reported?.email&&<button className="ml-2 mt-2 btn-outline !px-2 !py-1" onClick={()=>{s.adminDeleteComment(r.surface,r.itemId,r.commentId);banEmail(reported.email)}}>Remove & ban email</button>}</div>})}</div>}<div className="panel p-4"><h2 className="text-lg">People to connect with</h2>
     <ul className="mt-2 divide-y divide-outline-variant">{sugg.map(p=>{const status=s.connectionStatus(p.uid),connected=status==='connected';return <li key={p.uid} className="flex items-center gap-2 py-2"><Avatar p={p} size={32}/><Link to={`/u/${p.uid}`} className="flex-1 text-sm font-semibold">{p.name}<VerifiedBadge verified={p.verified}/><br/><span className="text-xs font-normal text-ink-2">{s.shared(p).length} shared interests</span></Link><button disabled={status==='requested'||status==='incoming'} onClick={async()=>{setError('');try{if(connected)await s.disconnect(p.uid);else await s.toggleConnect(p.uid)}catch(x){setError(x.message||'Could not update this connection.')}}} className="btn-outline !px-3 !py-1">{connected?'Disconnect':status==='requested'?'Request sent':status==='incoming'?'Check notifications':'Connect'}</button></li>})}</ul><Link to="/discover" className="mt-2 block text-sm underline underline-offset-4">See more</Link></div>
    <div className="panel p-4"><h2 className="text-lg">Teams looking for members</h2>{s.teams.slice(0,2).map(t=><Link key={t.id} to="/partners" className="mt-2 block text-sm"><b>{t.title}</b><br/><span className="text-xs text-ink-2">{t.event}</span></Link>)}</div></aside></div>}
